### ISSUE TITLE
[Help] Connect user

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-feed-flutter#101]
Hi,

In your example, you are connecting the user when app is started :
https://github.com/GetStream/stream-feed-flutter/blob/46c81823eea44e7e722adab5ded942463ededa3c/example/lib/main.dart#L12

In real uses case, we cant do it at launch, because user is not logged in yet..
Do you have some advice ?

Im also using chat, and is more convenient, because we dont need a cient instance (```final client = StreamFeedClient.connect(_key, token: Token(_user_token));```); we just need to do at some point:

https://github.com/GetStream/flutter-samples/blob/2306ae9ca35f46876b59106803018b72260094a3/packages/stream_chat_v1/lib/main.dart#L64

**Comment by xsahil03x** [comment]
Hey @Abacaxi-Nelson, yes ideally you should handle all this on a separate screen.

pseudocode

```dart
LoginScreen {
	final UserClient userClient;
	final StreamFeedClient feedClient;
	final StreamChatClinet chatClient;
	
	void login() {
	  // get user
	  final user = userClient.login();
	  // connect feed
	  feedClient.connect(key, user.token);
	  // connect chat
	  chatClient.connect(key, user.token);
	}
	
	Widget build() {
	  return Widget();
	}
	
}
```
