### ISSUE TITLE
Respost Issue

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#103]
I have a question. I am trying to do a repost/share as Facebook and Twitter do but when I use the code below I have issues. The activity is not copied to the target feed just the reaction does and not even the data that is added to the reaction.

```
streamClient!.reactions.add(
                                              'share', widget.post.id!,
                                              userId: streamClient
                                                  .currentUser!.userId,
                                              data: {
                                                'id': widget.post.id!,
                                              },
                                              targetFeeds: [
                                                feed.FeedId(
                                                    'user',
                                                    streamClient
                                                        .currentUser!.userId)
                                              ]);
```

**Comment by rlee1990** [comment]
@sachaarbonel do you have any ideas on this?

**Comment by sachaarbonel** [comment]
Can you expand on what you are trying to achieve? Add a count on the number of shares?
Also, what is your `getEnrichedActivities` query? Have you tried to add flags like `flags: EnrichmentFlags().withOwnReactions()`?

**Comment by rlee1990** [comment]
The idea would be to achieve what Facebook and Twitter and others do for a retweet or repost. The support team sent me what I added above but when I add the reaction to the person that pressed the share buttons feed it really does not provide any useful information it doesn't even have the reaction data.

**Comment by sachaarbonel** [comment]
Oh I see, this currently being worked on as we speak but basically in a nutshell (trying to peel the layers for you):
to get the reaction counts: https://github.com/GetStream/stream-feed-flutter/blob/a315369c9bbc417d0df91a993f3a50152ffc1127/packages/stream_feed_flutter/lib/src/widgets/buttons/reaction.dart#L41
to know if the user has already reacted: https://github.com/GetStream/stream-feed-flutter/blob/a315369c9bbc417d0df91a993f3a50152ffc1127/packages/stream_feed_flutter/lib/src/widgets/buttons/reaction.dart#L42-L43
https://github.com/GetStream/stream-feed-flutter/blob/a315369c9bbc417d0df91a993f3a50152ffc1127/packages/stream_feed_flutter/lib/src/widgets/buttons/reaction.dart#L95-L96
based on that information we know if we should add or remove that reaction kind and wich icon we should display (repost, comment or heart for example)
https://github.com/GetStream/stream-feed-flutter/blob/a315369c9bbc417d0df91a993f3a50152ffc1127/packages/stream_feed_flutter/lib/src/widgets/buttons/reaction.dart#L116
for a repost reaction, "kind" being "repost" https://github.com/GetStream/stream-feed-flutter/blob/a315369c9bbc417d0df91a993f3a50152ffc1127/packages/stream_feed_flutter/lib/src/widgets/buttons/repost.dart#L38
you can then fetch your enriched activities like this for example
https://github.com/GetStream/stream-feed-flutter/blob/a315369c9bbc417d0df91a993f3a50152ffc1127/packages/stream_feed_flutter/lib/src/widgets/feeds/flat.dart#L28

**Comment by rlee1990** [comment]
@sachaarbonel I think the issue is getting the activity as I already have the counts and added reactions but when I do this:
```
streamClient!.reactions.add(
                                              'share', widget.post.id!,
                                              userId: streamClient
                                                  .currentUser!.userId,
                                              data: {
                                                'id': widget.post.id!,
                                              },
                                              targetFeeds: [
                                                feed.FeedId(
                                                    'user',
                                                    streamClient
                                                        .currentUser!.userId)
                                              ]);
```
When trying to get the feed I have it set like this:
```
widget.streamClient!
        .flatFeed('user', widget.uid)
        .getEnrichedActivities(
            limit: 100,
            offset: 0,
            flags: EnrichmentFlags()
                .withReactionCounts()
                .withOwnReactions()
                .withRecentReactions()
                .withOwnChildren())
```

But the reaction is only there not the repost and the data that was added to the reaction is not there.

**Comment by sachaarbonel** [comment]
What do you mean by the reaction is only there not the repost? As I understand the reaction is the repost. 
Also, could you share some logs?

**Comment by rlee1990** [comment]
@sachaarbonel This is all that shows in the user feed for the person that reposted an activity 
<img width="448" alt="Screen Shot 2021-06-23 at 10 33 15 AM" src="https://user-images.githubusercontent.com/21372502/123115953-828f6b80-d40e-11eb-9daa-d4e7af5ee36a.png">

**Comment by rlee1990** [comment]
Notice how on my reaction I even add data but its not there:
```
streamClient!.reactions.add(
                                              'share', widget.post.id!,
                                              userId: streamClient
                                                  .currentUser!.userId,
                                              data: {
                                                'id': widget.post.id!,
                                              },
                                              targetFeeds: [
                                                feed.FeedId(
                                                    'user',
                                                    streamClient
                                                        .currentUser!.userId)
                                              ]);
```

**Comment by sachaarbonel** [comment]
It works fine for me, try to remove targetFeeds and let me know what you get

**Comment by rlee1990** [comment]
But then that defeats the point of a repost won't it. How will we get the activity?
Here is what I am trying to do.
User A adds a post to their user feed. The post shows on User B's timeline feed. User B clicks share or repost then the post from User B's timeline is added as an activity to User B's user feed and will show up on any feeds that follow User B's user feed.

**Comment by rlee1990** [comment]
@sachaarbonel I hope that helps

**Comment by rlee1990** [comment]
I think I see what is happening @sachaarbonel it looks like the post ID is added to the object field. I am trying to use that as a work around I will give that a go.

**Comment by sachaarbonel** [comment]
Thanks for elaborating on this. I shared your issue with a member of the react team I'll get back to you when I have more input on this

**Comment by rlee1990** [comment]
I got it to work it's odd but when I get the object for the reaction it then returns the whole post @sachaarbonel thanks for the help it got me to this. If the react team has a better approach I am all for it.
