### ISSUE TITLE
Subscribe to reactions ?

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-feed-flutter#104]
Hi
I'm using reactions for activity comments. Is there any way to subscribe for realtime reactions update ?

I know they is already subscription for feeds.

Thank you,
Nelson

**Comment by Abacaxi-Nelson** [comment]
In a faq, i saw:

We don't currently support this, but there are workarounds. When a reaction is added it can also be added to a hidden feed as an activity and notifications can be generated from that feed. Or, you can re-add the whole activity when a reaction is added. 

Real-time notifications are high on the priority list for 2021 features.

**Comment by sachaarbonel** [comment]
I'll ask the react team how they'd do this and share with you a nice code snippet :)

**Comment by sachaarbonel** [comment]
There is a tutorial for js, but none for dart yet. You can find it [here](https://getstream.io/activity-feeds/docs/node/notification_system/?language=javascript)

**Comment by Abacaxi-Nelson** [comment]
thanks @sachaarbonel
