### ISSUE TITLE
Update dev ?

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-feed-flutter#105]
Hi @sachaarbonel @xsahil03x
Is it possible to update more ofter dev branch ?
im developing an app on top of your packages, but last features are all on their branch.

No matter if bugs still exists, having features on develop will enable us to find bugs !

Thanks for your work :)
Have a nice day

**Comment by sachaarbonel** [comment]
Hey, @Abacaxi-Nelson so far in dev branch we are working on `stream_feed_flutter`and `stream_flutter_coer` which is mostly UI stuff, is that what you are interested in? It's very unstable right now. Hotfixes land on master

**Comment by Abacaxi-Nelson** [comment]
hey @sachaarbonel 
Yes this is what i need, no problem if it's instable..
some PR are open for 28 days..

**Comment by sachaarbonel** [comment]
Sorry about that we are still a pretty small team on feed. @xsahil03x and I will find some time to review the PRs this week

**Comment by Abacaxi-Nelson** [comment]
no worries @sachaarbonel :)

**Comment by Abacaxi-Nelson** [comment]
❤❤❤❤❤❤❤❤❤❤
