### ISSUE TITLE
[Bug] Subscribe (Experimental)

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-feed-flutter#109]
**Describe the bug**
Hi,
i get an error when i subscribe to a feed.

**What package are you using? What version?**
Develop branch

**What platform is it about?**
- [X] iOS

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

```dart
final userFeed = getstreamClient.flatFeed('timeline', uid);
      subscription = await userFeed.subscribe((message) {
        print('subscription $message');
      });
```

```dart
flutter: error Invalid argument(s): Missing app id, which is needed in order to subscribe feed
flutter: error #0      checkNotNull
package:stream_feed/…/util/extension.dart:36
#1      StreamFeedClientImpl._feedSubscriber
package:stream_feed/…/client/stream_feed_client_impl.dart:194
#2      Feed.subscribe
package:stream_feed/…/client/feed.dart:75
#3      FeedModel.fetchFirstList
package:amber_app/…/feed/feed_model.dart:47
#4      feedModelProvider.<anonymous closure>
package:amber_app/…/feed/feed.dart:51
#5      feedModelProvider.<anonymous closure>
package:amber_app/…/feed/feed.dart:42
```

Just sharing the bug, as i know its still experimental :)
By the way, it will be awesome to have a stream instead of a Subscription :)

Best regards,
Nelson

**Comment by xsahil03x** [comment]
@Abacaxi-Nelson in order to subscribe to feeds, you need to also pass AppId in the constructor which you can get from your project dashboard.

```dart
client = StreamFeedClient.connect(
      apiKey,
      secret: secret,
      appId: 'yourappid',
  );
```

**Comment by xsahil03x** [comment]
@sachaarbonel I think we can improve the error message and also append the solution in it.

**Comment by Abacaxi-Nelson** [comment]
Works !

**Comment by Abacaxi-Nelson** [comment]
hi @xsahil03x @sachaarbonel 
How is suppose to work the subscribe ? does it send each new activity one by one, or a batch of them ?

Thank you,
