### ISSUE TITLE
Subscribing To Notification Feed

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#110]
When subscribing to real-time updates of the notification feeds they also only return Enriched activities and not `NotificationGroup<Activity>`
Not sure if we are able to subscribe to them or not but that would be very useful.

**What platform is it about?**
- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Comment by sachaarbonel** [comment]
The UX we support right now is that you have to display a notification bell with a count (uses RealtimeTime type under the hood) and on click, it directs you to a ListView with a list of notifications (NotificationGroup<Activity>)

**Comment by rlee1990** [comment]
> The UX the backend supports as of now is that you have to display a notification bell with a count (uses RealtimeMessage type under the hood) and on click, it directs you to a ListView with a list of notifications (NotificationGroup<Activity>)

@sachaarbonel i can get notifications just fine the issue is when a use a notification feed and try to subscribe to real-time updates the return type is wrong.
