### ISSUE TITLE
getEnrichedActivities - Filter

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-feed-flutter#111]
**Describe the bug**
Hi team,
im using filters when getting activities.

```dart
getEnrichedActivities(
            limit: _itemsMaxSize,
            filter: filter.idGreaterThanOrEqual(lastActivityId),
```
My problem is 
if i keep: ```filter.idGreaterThanOrEqual(lastActivityId)``` im seeing my activity => Great
```dart
activityId:2157117b-dd7b-11eb-a6fd-12d73b08236b newItems => [2157117b-dd7b-11eb-a6fd-12d73b08236b]
```

but, if i switch to ```filter.idLessThanOrEqual(lastActivityId)``` im not seeing anymore the activity, i see old activities only
```dart
activityId:2157117b-dd7b-11eb-a6fd-12d73b08236b newItems => [ac4ed14a-dd67-11eb-b60d-128a130028af, 1212b7b7-dd65-11eb-9337-0a1200300037, e8f71af1-dd63-11eb-92b9-0a1200300037, dcd17743-dd04-11eb-9c64-0ae838defca7, 861fc8c3-dd04-11eb-b74c-128a130028af]
```

**What package are you using? What version?**
develop

**What platform is it about?**
- [ ] Android
- [X ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Additional context**
Dont know why, but after some time... ```idLessThanOrEqual``` works :
```dart
activityId:2157117b-dd7b-11eb-a6fd-12d73b08236b newItems => [2157117b-dd7b-11eb-a6fd-12d73b08236b, 86944ce2-dd78-11eb-a1e9-0a1200300037, dbe68432-dd77-11eb-81ad-128a130028af, d8a3e027-dd76-11eb-a495-0ae838defca7, b85db3c1-dd76-11eb-8f6f-0a0d7a10423a]
```

Is there some cache involve ?
Best regards,
Nelson

**Comment by Abacaxi-Nelson** [comment]
maybe i'm misunderstand API 
```dart
Future<Activity> getActivityDetail(String activityId) async {
    final activities = await getActivities(
        limit: 1,
        filter: Filter()
            .idLessThanOrEqual(activityId)
            .idGreaterThanOrEqual(activityId));
    return activities.first;
  }
```

Why do you need to use both ```idLessThanOrEqual``` ```idGreaterThanOrEqual```
```idLessThanOrEqual``` should return activityId, and limit=1 force API to return only one...

Why using both ?

**Comment by sachaarbonel** [comment]
Think of it as something that gets interpreted by the backend as: `SELECT * FROM activities WHERE activity_id >= inputid AND activity_id <= inputid  LIMIT 1`;

**Comment by Abacaxi-Nelson** [comment]
@sachaarbonel kind of optimzation.

But ```idLessThanOrEqual``` ```idGreaterThanOrEqual``` are not supposed to a list which contains at least the ```activityId``` passed ?

that's not the case in my test..

**Comment by Abacaxi-Nelson** [comment]
Oooh i get it !
Activities must have a "time" supplied :
```dart
feed.Activity(
      actor: client.currentUser!
      time: DateTime.now(),
```

**Comment by sachaarbonel** [comment]
Well spot!

**Comment by sachaarbonel** [comment]
Do you think a doc on top of the field `idGreaterThanOrEqual` inf `Filter` would help future users with this type of issue?

**Comment by Abacaxi-Nelson** [comment]
Yes for sure.
More over, adding it also when adding activities.. this field could be mandatory
