### ISSUE TITLE
api_key is missing error in example project

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [GetStream/stream-feed-flutter#117]
**Describe the bug**

I download the example folder and run, then initialize API key, token and appID, 
```
`  final client = StreamFeedClient.connect(
    _key,
    token: Token("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTEzNDYxMSJ9.ROo1ALbUo03TEeTgd2dMZe6xSfRnenQsHtZUncqRXLU"),
    appId: "1134611",
  );`
```
but this gives this error when I click any user, for example, Sahil Kumar or any other.

```
`flutter: *** Request ***
flutter: uri: https://api.stream-io-api.com/api/v1.0/user/?get_or_create=true&api_key=&location=unspecified
flutter: method: POST
flutter: responseType: ResponseType.json
flutter: followRedirects: true
flutter: connectTimeout: 10000
flutter: sendTimeout: 0
flutter: receiveTimeout: 10000
flutter: receiveDataWhenStatusError: true
flutter: extra: {}
flutter: headers:
flutter:  stream-auth-type: jwt
flutter:  x-stream-client: stream-feed-dart-client-ios-0.2.2
flutter:  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTEzNDYxMSJ9.ROo1ALbUo03TEeTgd2dMZe6xSfRnenQsHtZUncqRXLU
flutter:  content-type: application/json; charset=utf-8
flutter: data:
flutter: User(sahil-kumar, {first_name: Sahil, last_name: Kumar, full_name: Sahil Kumar}, null, null, null, null)
flutter:
flutter: *** DioError ***:
flutter: uri: https://api.stream-io-api.com/api/v1.0/user/?get_or_create=true&api_key=&location=unspecified
flutter: DioError [DioErrorType.response]: Http status error [401]
#0      DioMixin.assureDioError
package:dio/src/dio_mixin.dart:819
#1      DioMixin._dispatchRequest
package:dio/src/dio_mixin.dart:678
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
package:dio/src/dio_mixin.dart:1
<asynchronous suspension>
flutter: uri: https://api.stream-io-api.com/api/v1.0/user/?get_or_create=true&api_key=&location=unspecified
flutter: statusCode: 401
flutter: headers:
flutter:  connection: keep-alive
flutter:  content-type: text/plain; charset=utf-8
flutter:  access-control-allow-origin: *
flutter:  date: Thu, 22 Jul 2021 11:51:33 GMT
flutter:  server: nginx
flutter:  content-length: 168
`
```

How can I solve this problem ? 

**What version of Flutter do you use?**
Flutter 2.2.3
**What package are you using? What version?**
version 0.2.2

**What platform is it about?**
- [ ] Android
- [ ] iOS

✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-AZ)
    • Flutter version 2.2.3 at /Users/shahmirzali/Development/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/shahmirzali/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone (mobile) • c47d4be7167357fd9af36d2acb585f38cc997040 • ios            • iOS 14.4.2
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

**Comment by sachaarbonel** [comment]
Hey @Shahmirzali-Huseynov thanks for submitting an issue. Sounds like you didn't provide an api key. In the sample project we retrieve it from an environment variable that you have to set.

**Comment by Shahmirzali-Huseynov** [comment]
@sachaarbonel thanks for support, but i set API key, but not working :(

**Comment by sachaarbonel** [comment]
By set you mean hardcoded or set the env? If it is the later it's possible that on mobile it doesn't work. Ialso have something else in mind: is it your API key (copy pasted from your dashboard) or the API key from the [tutorial](https://getstream.io/activity-feed/sdk/flutter/tutorial/)?

**Comment by MisterJimson** [comment]
I ran into this too. You need to match the ID of the user you are clicking on with the ID you used to generate the token.

In my use case, I generated the user token like this in node.
```js
const userToken = client.createUserToken('test');
```

And after I copied it into the Flutter app for testing, none of the user buttons worked. So I went into `app_user.dart` and modified Sahil's id to match mine.

```dart
const AppUser.sahil()
    : id = 'test',
      name = 'Sahil Kumar',
```

**Comment by xsahil03x** [comment]
@Shahmirzali-Huseynov the above solution which @MisterJimson shared will most probably solve your issue.
