### ISSUE TITLE
Log Level?

### ISSUE THREAD

**Issue by ObserverMoment** [GetStream/stream-feed-flutter#128]
Hey, a quick one...are we able to reduce the StreamFeedClient log level? I seem to be getting every line from every call dumped into my VSCode debug console - it would be nice if we could turn this off when not directly debugging GetStream SDK, as it just dominates the log and drowns out everything else.

Thanks,

Rich

**Comment by sachaarbonel** [comment]
Hey @ObserverMoment, this is now released in v0.3.0, you can disable log that way:
`var client = StreamFeedClient.connect(apiKey, token: Token('userToken'), logLevel: Level.OFF);`

**Comment by ObserverMoment** [comment]
Nice! Thanks @sachaarbonel
