### ISSUE TITLE
Const errors

### ISSUE THREAD

**Issue by akul1994** [GetStream/stream-feed-flutter#135]
**Describe the bug**
Getting multiple constant constructor errors (Activity class,FeedIdClass)

Code is just me testing the sdk out, ignore the scrappy code

```  
var user1 = StreamFeedHelper.client
              .flatFeed('user', UserHelper.user?.userUuid ?? "");
          var id = StreamFeedHelper.client.currentUser;
          print(id);
          const activity = Activity(
              actor:  StreamFeedHelper.client.currentUser.ref ,
              verb: 'post',
              object: 'Place:42',
              to: [
              FeedId.id('timeline:${UserHelper.user?.userUuid}')
              ],
              extraData: {"message": "Hello There"});
          var activity11 =  await user1.addActivity(activity);
          print("Activity sent $activity11");
```

<img width="403" alt="Screenshot 2021-09-01 at 11 02 20 PM" src="https://user-images.githubusercontent.com/9698473/131718043-ce08b9e8-6107-4404-a233-97668c2adc67.png">
<img width="489" alt="Screenshot 2021-09-01 at 11 08 10 PM" src="https://user-images.githubusercontent.com/9698473/131718062-5d9c8f66-7454-4218-8206-6889d2548925.png">
<img width="742" alt="Screenshot 2021-09-01 at 11 12 13 PM" src="https://user-images.githubusercontent.com/9698473/131718418-2165ed22-faa0-40e5-989f-3f7600024f46.png">

**What version of Flutter do you use?**
v2.13.4

**What package are you using? What version?**
stream feed 0.2.3

**What platform is it about?**
- [ yes] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**a copy of `flutter doctor --verbose`**

**To Reproduce**
Initialise an activity or feedid object with a value stored in an object

**Expected behavior**
It should let me initialise the object

**Screenshots**

**Comment by xsahil03x** [comment]
:neutral_face:
```dart
var user1 = StreamFeedHelper.client.flatFeed('user', UserHelper.user?.userUuid ?? "");
var id = StreamFeedHelper.client.currentUser;
print(id);
final activity = Activity(
       actor:  StreamFeedHelper.client.currentUser.ref ,
       verb: 'post',
       object: 'Place:42',
       to: [FeedId.id('timeline:${UserHelper.user?.userUuid}')],
       extraData: {"message": "Hello There"}
   );
var activity11 =  await user1.addActivity(activity);
print("Activity sent $activity11");
```
