### ISSUE TITLE
[Bug] FormatException: Invalid character (at character 1)<p>Please try again in 30 seconds===^

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-feed-flutter#137]
**Describe the bug**
I got during 5 min:

**[Bug] FormatException: Invalid character (at character 1)<p>Please try again in 30 seconds===^**

And then, back to normal.

I reload the app so i lost debug.
But, code which failed was:

https://github.com/GetStream/stream-feed-flutter/blob/e16110d152f0ac62c99d5e0b8ae13f67115b3d40/packages/stream_feed/lib/src/client/stream_feed_client_impl.dart#L58

**What version of Flutter do you use?**
Flutter 2.2.2

**What package are you using? What version?**
git develop

**What platform is it about?**
- [ ] iOS

**To Reproduce**
```dart
final client = feed.StreamFeedClient.connect(
        apiKey,
        token: feed.Token(response.body),
        appId: 'XXXX',
      );
```

I check getstream status and everything was fine...

**Comment by sachaarbonel** [comment]
Hey, @Abacaxi-Nelson thanks for opening an issue. That's a weird bug that would be hard to replicate. Are you sure it's coming from us and not from one of your services (auth for example)? Let me know if it occurred again
