### ISSUE TITLE
Getting Current Stream User Issue

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#177]
**Describe the bug**
When calling `widget.streamClient.currentUser` It returns null. It worked before switching to the lastest version.
I have tried all sorts of ways to set the user but the issue reamins.
**What version of Flutter do you use?**
2.5.3

**What package are you using? What version?**
0.4.0

**What platform is it about?**
- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Comment by HayesGordon** [comment]
Hi, @rlee1990. We will release a new version soon to make this a bit more clear.

Before calling `.currentUser` you now need to set a user first, using `streamClient.setUser(User('id', data: data), 'user-token');`

**Comment by rlee1990** [comment]
@HayesGordon I did that and I still get a null user:
```
streamClient.setUser(
        feed.User(id: u, data: {
          'name': currentUser.data!.value.name,
          'image': currentUser.data!.value.currentProfileImage
        }),
        feed.Token(currentUser.data!.value.currentToken!));
```

**Comment by rlee1990** [comment]
@sachaarbonel Any idea at to what the issue could be?

**Comment by sachaarbonel** [comment]
Hey sorry for the late response. As @HayesGordon said we did a change in this release (0.4.0) to be able to swap a User token at runtime (think of using a different profile for example) without instantiating StreamFeedClient again.
I think the reason why you have an error is that you try to setUser with data from currentUser (currentUser.data etc), but currentUser is not "set" yet. Maybe try to hardcode the value of name, image and token and see if it works

**Comment by rlee1990** [comment]
@sachaarbonel sorry for the confusion the currentUser in the code above is from Firebase which I get from a riverpod provider. I have confirmed that that information is coming in and that the setUser function is running.

**Comment by sachaarbonel** [comment]
oh, I see. Are you awaiting `setUser`? It's a future now, so might be it

**Comment by rlee1990** [comment]
@sachaarbonel Yes I am.
I set the setUser up in a FutureProvider for Riverpod.
The watch it here:
```
return watch(streamUser).when(
              data: (sUser) {
                final streamClient = context.read(client);
                switch (data.currentAccount) {
                  case 'personal':
                    return ScreenTypeLayout(
                      mobile: TabView(
                        currentUser: data,
                        streamClient: streamClient!,
                      ),
                    );
                  default:
                    return ScreenTypeLayout(
                      mobile: TabView(
                        currentUser: data,
                        streamClient: streamClient!,
                      ),
                    );
                }
              },
```

**Comment by sachaarbonel** [comment]
Wait so sUser is null inside your data callback?

**Comment by rlee1990** [comment]
@sachaarbonel nope this is what it returns:
`I/flutter (25177): SUser data: StreamUser(ytmORLAvAiWvYGt2jyL2GzeENMc2_personal, 2021-08-19 16:59:15.430621Z)`

**Comment by rlee1990** [comment]
It looks like the data might be coming back as null. I can call 
```
final u = widget.streamClient
        .user('${widget.user.uid}_${widget.user.currentAccount}');
```

With me putting in the username and trying to print u.data it returns null.

**Comment by rlee1990** [comment]
Any update on this?

**Comment by sachaarbonel** [comment]
Hey, @rlee1990 sorry I thought you meant User was null. The underlying data is. A workaround is to call `profile` just after you `setUser`

**Comment by rlee1990** [comment]
@sachaarbonel when you say call profile is this a get stream function?

**Comment by rlee1990** [comment]
Nevermind

**Comment by sachaarbonel** [comment]
yes it's a method from StreamUser
`await currentUser.profile()`

**Comment by rlee1990** [comment]
I am still having an issue. @sachaarbonel is there an example anywhere so I can try to compare?

**Comment by rlee1990** [comment]
I tried a few more times and still get the same issue I don't think the current user is being set. 
@sachaarbonel

**Comment by rlee1990** [comment]
Any update @HayesGordon or @sachaarbonel I can't seem to find a solution.

**Comment by rlee1990** [comment]
Hi @sachaarbonel any other recommendations?

**Comment by xsahil03x** [comment]
> It looks like the data might be coming back as null. I can call
> 
> ```
> final u = widget.streamClient
>         .user('${widget.user.uid}_${widget.user.currentAccount}');
> ```
> 
> With me putting in the username and trying to print u.data it returns null.

@rlee1990 , After setting the user successfully, you should use 
`client.currentUser` to get the connected user.

`client.user` is used to create a new user instance. that's why `user.data` returns null.

**Comment by rlee1990** [comment]
Hi @xsahil03x Im still having the same issue

**Comment by rlee1990** [comment]
This is my riverpod provider:
```
final streamUser = FutureProvider.autoDispose((ref) async {
  final streamClient = ref.read(client);
  final currentUser = ref.watch(userAccount);
  if (streamClient != null && currentUser.asData!.value.uid != null) {
    print('Feed User set.');
    var u =
        '${currentUser.asData!.value.uid}_${currentUser.asData!.value.currentAccount}';
    final user = await streamClient.setUser(
        feed.User(
          id: u,
        ),
        feed.Token(currentUser.asData!.value.currentToken!));
    await streamClient.currentUser!.profile();
    return user;
  }
  return Future.value();
});
```
and the function where I first get a user:
```
widget.streamClient.currentUser!.get().then((value) {
      var data = value.data;
      
      setState(() {
        image = data!['photo'] as String;
        name = data['name'] as String;
      });
      fetchStories();
    });
```
@xsahil03x
