### ISSUE TITLE
Error Trying To Subscribe To A Feed

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#189]
I keep getting the below error:
`Unhandled Exception: Invalid argument(s): Missing app id, which is needed in order to subscribe feed
`
I see in the code that the internal subscriber requires a token but the public-facing Subscribe function does not give an option to put one.

**Comment by sachaarbonel** [comment]
Hey @rlee1990 thanks for opening an issue, what version are you using? Since 0.5.0, the userToken is set with  `setUser(user,token)`. Are you instantiating the client with an appId? `StreamFeedClient(apiKey,appId:appId)`?

**Comment by rlee1990** [comment]
I am using 0.5.0 @sachaarbonel 
And I see the issue Looks like the client doesn't prompt when only the secret is provided forgot to check there 🤦🏽‍♂️
