### ISSUE TITLE
Better Pagination Support

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#208]
It would be nice to get the feed items with a page number and a max page number when we get activities so we can know when the last page is showing and to not try and fetch more pages.

**Comment by rlee1990** [comment]
The pagination example on the feed docs for flutter show this under JavaScript:
```
{ 
  results: [], 
  next: '/api/v1.0/feed/<< feed_group >>/<< feed_id >>/?api_key=<< api_key >>&id_lt=<< next_activity_id >>&limit=<< activity_limit >>' 
} 

```
If we are able to get the next id that would also help.

**Comment by rlee1990** [comment]
@sachaarbonel is there any chance this could be done at least the second option?

**Comment by rlee1990** [comment]
@HayesGordon is this possible?

**Comment by sachaarbonel** [comment]
Hey @rlee1990 sorry I was a bit busy transitioning to DevRel, taking a look right now

**Comment by rlee1990** [comment]
@sachaarbonel no worries just didn't know if anyone had seen this.

**Comment by sachaarbonel** [comment]
Hey, @rlee1990 I have an ongoing fix in #210, let me know if it works for you. The API is a bit rough for now but it should work in the meantime

**Comment by rlee1990** [comment]
@sachaarbonel thanks for the update that would work.

**Comment by rlee1990** [comment]
@sachaarbonel any clue when this will be updated to the master branch?

**Comment by sachaarbonel** [comment]
Did you have a chance to try it out? If it works for you then I can just release it now

**Comment by rlee1990** [comment]
@sachaarbonel was trying it today but got this error 
```
Could not find a file named "pubspec.yaml" in https://github.com/GetStream/stream-feed-flutter.git 7a92bc6f98e6b2d074ecffa28203b83ad06c3874.
pub get failed (1; Could not find a file named "pubspec.yaml" in https://github.com/GetStream/stream-feed-flutter.git 7a92bc6f98e6b2d074ecffa28203b83ad06c3874.)
```

**Comment by rlee1990** [comment]
@sachaarbonel it does work. I do have a question.
Is it possible to also pass I boolean or just a null idLT if there are not any more activities in that feed? as of now I get the same idLT?
If not I am sure I can create a workaround.

**Comment by rlee1990** [comment]
@sachaarbonel I did find a workaround on my end by just checking if the idLT matches the previous one so this is working as I would expect it to.

**Comment by rlee1990** [comment]
@sachaarbonel will this also be added for aggregatedFeeds?

**Comment by rlee1990** [comment]
@sachaarbonel is it possible to have this option for aggregated Feed types also?

**Comment by sachaarbonel** [comment]
Hey @rlee1990 sure I'll work on it

**Comment by rlee1990** [comment]
@sachaarbonel any update on this?

**Comment by sachaarbonel** [comment]
We are releasing it this week along with support for pagination in [core]( https://github.com/GetStream/stream-feed-flutter/pull/222)

**Comment by rlee1990** [comment]
Thanks

**Comment by rlee1990** [comment]
@sachaarbonel any news on this?

**Comment by rlee1990** [comment]
@sachaarbonel Any updates on this?
