### ISSUE TITLE
Version 0.5.1 create infinite build when listening for realtime, where 0.5.0 is not

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-feed-flutter#209]
**Describe the bug**
I hate to create such issues, without nothing to share; i was no able to catch the bug... (no logs..)
I updates stream_feed to 0.5.1, and infinite builds starts..
Only way to stop this, was to remove this block:

```dart
subscription = await userFeed.subscribe((message) {
        handleNewPost(message);
      });
```

**What version of Flutter do you use?**
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git

**What package are you using? What version?**
0.5.1

**What platform is it about?**
- [ ] Android
- [ X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**a copy of `flutter doctor --verbose`**

**To Reproduce**

**Logs **
Sorry no logs available...

Paste the output of running `flutter doctor -v` here.
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.0.1 21A559 darwin-arm, locale fr-FR)
    • Flutter version 2.10.3 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/nelsonnunes/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • C4DBA570-CF7F-4DDC-96EC-32787283C1C0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Additional context**

**Comment by HayesGordon** [comment]
Hi, @Abacaxi-Nelson we tried to replicate this but could not. On adding new activities our subscription is only triggered once as expected. Can you share a more complete example of how and when you're calling `.subscribe`?

**Comment by Abacaxi-Nelson** [comment]
I change some internal state management.
I will retry, maybe i fixed it :)
