### ISSUE TITLE
No longer can get a list of followers

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#213]
I am using `stream_feed: ^0.5.1` on android and ios. 
When I run ```
streamFeedClient
          .flatFeed("timeline", widget.accountToCheck)
          .following(limit: 100, offset: 0)
```
I receive this error: ```
"You do not have permission to do this, you got this error because there are no policies allowing this request o
flutter: (2022-03-25 15:23:45.711296) 🚨 📜 ║         n this application. Please consult the documentation [https://getstream.io/docs/]()"
flutter: (2022-03-25 15:23:45.711413) 🚨 📜 ║         status_code: 403,
flutter: (2022-03-25 15:23:45.711511) 🚨 📜 ║         code: 17,
flutter: (2022-03-25 15:23:45.711601) 🚨 📜 ║         exception: "NotAllowedException",
flutter: (2022-03-25 15:23:45.711675) 🚨 📜 ║         duration: "0.15ms",
flutter: (2022-03-25 15:23:45.711763) 🚨 📜 ║         more_info: "[https://getstream.io/docs/api_error_responses]()"
```
I am just having any user that visits someone's page or even their own page to be able to see who that person follows or who follows that person. This was working before and now it is not.

**Comment by rlee1990** [comment]
@sachaarbonel Nope I haven't made any request recently.

**Comment by rlee1990** [comment]
Any updates on this?

**Comment by sachaarbonel** [comment]
Nothing changed backend-wise. If you haven't changed anything on your side then I would suggest asking for support for changing the policy like suggesting in this comment that seems similar to your issue https://github.com/GetStream/stream-feed-flutter/issues/112#issue-938894908

**Comment by rlee1990** [comment]
@sachaarbonel thanks.

**Comment by sachaarbonel** [comment]
Another option is on the serverside to generate a token with enough claims for your users. See: https://github.com/GetStream/stream-feed-flutter/blob/4e8b237eb6918bf90d68526611584abda48341da/packages/stream_feed/lib/src/client/feed.dart#L275
