### ISSUE TITLE
Get An Activity By An Extra Field

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#218]
It would be nice to get an activity by an extra field. Say like if you have a pinned activity but its not the first 25 or even the first 100 activities returned for the feed it would be nice to be able to search on a key word like pinned and get that one to show.

**Comment by sachaarbonel** [comment]
Hey @rlee1990, you can achieve the desired "pinned activities" effect by adding a ranking method to your feed group in your dashboard. Check out this article:
https://getstream.io/blog/getting-started-ranked-feeds-getstream-io/

**Comment by rlee1990** [comment]
I can create that but the issue is retrieving the one that is pinned if it's say activity 200 in a feed and we only get the first 100 at a time. It would be hard to have the pinned activity to always be on top @sachaarbonel

**Comment by rlee1990** [comment]
Unless I am doing it wrong or misunderstanding

**Comment by sachaarbonel** [comment]
Do you have something like this in your dashboard?
<img width="1127" alt="Capture d’écran 2022-04-04 à 17 32 19" src="https://user-images.githubusercontent.com/18029834/161635838-cb384620-7f08-4b19-bd5b-386ecf3cd37b.png">

**Comment by rlee1990** [comment]
Yes I do

**Comment by rlee1990** [comment]
I will try and test it again

**Comment by rlee1990** [comment]
@sachaarbonel so I ran a test and the pinned post does get loaded with the first pull for activities. For example if I have 12 post and the 12th is the newest and 1 is the oldest. Lets say I pinned post number 1. If I set the limit of post to load at the start to 10 it will load post 12 - 2 and the pinned post does not get pulled.

**Comment by rlee1990** [comment]
@sachaarbonel okay thanks will do and I guess for now I will add a work around.
