### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by mahboubii** [GetStream/stream-feed-flutter#3]
## Client
- [x] Upload Image `POST /images`
- [x] Process Image `GET /images?url=&...`
- [x] Upload File `POST /files`
- [x] RefreshCDNUrl `POST /files/refresh`
- [x] GetActivities `GET /activities`
- [x]  GetEnrichedActivities `GET /enrich/activities`
- [x] OG `GET /og`
- [x] PersonalizedFeed `GET /enrich/personalization/feed` (should it be moved to feed?)

## User
- [x] Create `POST /user`
- [x] Get `GET /user/${userID}`
- [x] Delete `DELETE /user/${userID}`
- [x] Update `PUT /user/${userID}`
- [x] GetOrCreate => User.Create
- [x] Profile => User.Get

## Feed
- [x] AddActivity `POST /feed/${feedType}/${feedID}`
- [x] RemoveActivity `DELETE /feed/${feedType}/${feedID}`
- [x] AddActivities `POST /feed/${feedType}/${feedID}`
- [x] Get `GET /feed/${feedType}/${feedID}` or `GET enrich/feed/${feedType}/${feedID}`
- [x] GetActivityDetail => Feed.Get

### Follow
- [x] [Follow `POST /feed/${feedType}/${feedID}/following`](https://github.com/GetStream/stream-feed-flutter/blob/2ecf4e8a0e6c1ebdf617dfbe4cb721b4d23220b1/packages/stream_feed/lib/src/core/api/feed_api_impl.dart#L49)
- [x] Unfollow `DELETE /feed/${feedType}/${feedID}/following/${targetFeedId}`
- [x] Following `GET /feed/${feedType}/${feedID}/following`
- [x] Followers `GET /feed/${feedType}/${feedID}/followers`
- [x] FollowStats `GET /stats/follow`

### Realtime
- [x] Faye Client
- [x] Subscribe 
- [x] Unsubscribe

## Reaction
- [x] Add `POST /reaction`
- [x] AddChild `POST /reaction`
- [x] Get `GET /reaction/${reactionID}`
- [x] Delete `DELETE /reaction/${reactionID}`
- [x] Filter `GET /reaction/...`
- [x] Update `PUT /reaction/${reactionID}`

## Collections
- [x] Get `GET collections/${collectionName}/${itemID}`
- [x] [Add `POST collections/${collectionName}/${itemID|null}`](https://github.com/GetStream/stream-feed-flutter/blob/2ecf4e8a0e6c1ebdf617dfbe4cb721b4d23220b1/packages/stream_feed/lib/src/core/api/collections_api_impl.dart#L124)
- [x] Update`PUT collections/${collectionName}/${itemID}`
- [x] Delete `DELETE collections/${collectionName}/${itemID}`

## Analytics
**Analytics has different base url from main client**
- [x] TrackImpressions `POST /impression`
- [x] TrackEngagements `POST /engagement`

## Files
Added to Client
## Images
Added to Client
## Personalization
Skipped
## Batch Operations
Skipped

**Comment by sachaarbonel** [comment]
closing this now, we released the package on pub [check it out ](https://pub.dev/packages/stream_feed)
