### ISSUE TITLE
The Class User Has Conflicts

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#53]
The class User conflicts with the Firebase class name of User. We can work around it but might I suggest changing the name to streamUser of feedUser?

**Comment by Nash0x7E2** [comment]
Hey! Thank you for taking the time to file a bug, our team has a PR in progress which addresses this issue. 

PR: #43

**Comment by xsahil03x** [comment]
Closing as fixed in #43
