### ISSUE TITLE
Example App ?

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-feed-flutter#57]
Hi team,
So happy to have a feed plugin now ❤️

Is there any plan to create an example app like the chat does ?

Thank you,
Nelson

**Comment by sachaarbonel** [comment]
Hey Nelson, we got you! There is a tutorial [here](https://github.com/GetStream/flutter-feeds-tutorial)

**Comment by Abacaxi-Nelson** [comment]
hey @sachaarbonel 
Yes, but an example has much more:

- Reusable component
- State management
- Edge case handle

:)
