### ISSUE TITLE
Actor Id On Add Activity

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#60]
Can we remove the need to add SU as part of an actor ID. Is there a certain reason for this? I use that actor ID when getting the activities and would have to rewrite code to remove that in a lot of places. If it is something that is needed I understand just trying to better understand the use of it.

**Comment by sachaarbonel** [comment]
The server needs this for enrichment however an easier way to create a reference is by doing this: `client.currentUser.ref`

**Comment by rlee1990** [comment]
Cool thanks @sachaarbonel

**Comment by xsahil03x** [comment]
@rlee1990 passing a `ref` is optional. You only pass it when you want to enrich the activity.
