### ISSUE TITLE
NotificationGroup Issue

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#80]
The NotificationGroup model is not publicly available to import. As of now I have to manually add 
`import 'package:stream_feed/src/core/models/group.dart';` Then I get this warning for doing so:
`Don't import implementation files from another package.`

**Comment by xsahil03x** [comment]
Hey @rlee1990, can you also share what are you trying to do?

**Comment by sachaarbonel** [comment]
He is probably trying to make a widget accept a NotificationGroup parameter, which is reasonable. Opened a fix #81

**Comment by sachaarbonel** [comment]
Hey @rlee1990 the fix is now available in the latest version: `stream_feed: ^0.2.1`. Thanks for your valuable feedback
