### ISSUE TITLE
Feed Subscribe Issue 

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#96]
When you receive the new activities the data is of type Enriched Activity but the data only has the fields of Type activity.

This is an enriched activity when I first get all activities:
`EnrichedActivity(EnrichableField({created_at: 2021-06-07T02:16:12.451786Z, updated_at: 2021-06-07T02:16:12.451786Z, id: yveXfteo6tTV674YBzeGAHlg8xC2personal, data: {gender: Male, name: rickey lee, photo: https://firebasestorage.googleapis.com/v0/b/fire-snab.appspot.com/o/profile-image-placeholder.png?alt=media&token=b17598bb-a510-4167-8354-ab75642ba89e}}), EnrichableField(texted), posted, EnrichableField(), null, , 3270aa64-cbb3-11eb-8080-8001543e6aa3, 2021-06-12 19:20:07.076106, null, null, EnrichableField(user:yveXfteo6tTV674YBzeGAHlg8xC2personal), null, {atSigns: {}, files: [], hasFile: false, latest_reactions_extra: {}, text: Hello everyone, toExpire: false}, {}, {}, {})`

This is the data I get from the subscription:
`{actor: {created_at: 2021-06-07T02:16:12.451786Z, data: {gender: Male, name: rickey lee, photo: https://firebasestorage.googleapis.com/v0/b/fire-snab.appspot.com/o/profile-image-placeholder.png?alt=media&token=b17598bb-a510-4167-8354-ab75642ba89e}, id: yveXfteo6tTV674YBzeGAHlg8xC2personal, updated_at: 2021-06-07T02:16:12.451786Z}, verb: posted, object: texted, foreign_id: , time: 2021-06-12T19:44:24.863293, atSigns: {}, files: [], hasFile: false, text: Hi, toExpire: false}`

**Comment by sachaarbonel** [comment]
Hey @rlee1990 I don't quite get your issue, as the data you get from the subscription is enriched, at least the field actor is. Can you elaborate?

**Comment by rlee1990** [comment]
@sachaarbonel the enriched activities that we get from fetching them come with fields like own reactions and things like that even if null and we can use that with our local post modal but when we subscribe to a feed it does not contain any of that.

**Comment by sachaarbonel** [comment]
So as @xsahil03x said in this comment things like `own_reaction`, `latest_reactions`, etc are not supported for subscriptions by the backend thus not by the SDK.
https://github.com/GetStream/stream-feed-flutter/issues/89#issuecomment-858901924

I'll add this to our docs as I agree it's not clear

A workaround you could do is to fetch those fields in particular via the  client `stream_feed`

**Comment by rlee1990** [comment]
Thanks.
