### ISSUE TITLE
Stream Analytics 

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-feed-flutter#98]
Is stream Analytics included in the feeds sdk for flutter or the chat sdk? If so is there a way to set it up? I do not see anything in the docks for setting it up for flutter/dart.

**Comment by sachaarbonel** [comment]
Hey @rlee1990, sorry about that, just realised that it is documented in the code but not on our website. We'll update asap. But in a nutshell this is how you would do it
```dart
   final analytics = AnalyticsClient(apiKey,
       userToken: token);
   await analytics.trackEngagement(Engagement(
       content: {"foreign_id": "tweet:34349698"},
       label: "click",
       userData: UserData("test", "test"),
       feedId: FeedId("user", "thierry")));
   ```

If you are interested in how we will do it in Flutter take a look at this (work in progress) implementation [here](https://github.com/GetStream/stream-feed-flutter/blob/cbb43b8de9af0c7383cdeaddd03395a679f4dace/packages/stream_feed_flutter_core/lib/src/stream_feed_core.dart#L107):

**Comment by rlee1990** [comment]
Thank you.
